// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr_oIYW8Yyr8PNz8s5tlaqLpyhezJus4s',
    appId: '1:1044317453338:web:87eaddfe476c16c64d25a3',
    messagingSenderId: '1044317453338',
    projectId: 'mohanadproject-295fe',
    authDomain: 'mohanadproject-295fe.firebaseapp.com',
    storageBucket: 'mohanadproject-295fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwAtFyrsyFfrBDnQIcT14wePZiqtYGXCM',
    appId: '1:1044317453338:android:ce3f6735eb4f08ad4d25a3',
    messagingSenderId: '1044317453338',
    projectId: 'mohanadproject-295fe',
    storageBucket: 'mohanadproject-295fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeLb-Db72a4Lu447Sa67Lcb1cfsk3wubk',
    appId: '1:1044317453338:ios:245b5972c73c9a224d25a3',
    messagingSenderId: '1044317453338',
    projectId: 'mohanadproject-295fe',
    storageBucket: 'mohanadproject-295fe.appspot.com',
    iosClientId: '1044317453338-hcfe3vvjqhvsn7e0bhnu549r47sl9n6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.mohanad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeLb-Db72a4Lu447Sa67Lcb1cfsk3wubk',
    appId: '1:1044317453338:ios:245b5972c73c9a224d25a3',
    messagingSenderId: '1044317453338',
    projectId: 'mohanadproject-295fe',
    storageBucket: 'mohanadproject-295fe.appspot.com',
    iosClientId: '1044317453338-hcfe3vvjqhvsn7e0bhnu549r47sl9n6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.mohanad',
  );
}
